name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["main"]

jobs:
  example:
    name: Ubuntu20.04
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v3
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
