name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["main"]

jobs:
  example:
    name: Ubuntu20.04
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH
        # You may pin to the exact commit or the version.
        # uses: Tofandel/ssh-server-action@14e8cd7378e39c4fe5035e7a8ff1b2742e7b24a5
        uses: Tofandel/ssh-server-action@v1.0.0
        with:
          # The hostname of the ssh server
          hostname: ivanvps
          # The internal port of the ssh server
          port: 22
          # The user name
          user_name: ivangabriel
          # The user password
          user_password: ivangabriel
